version: '3.9'

services:
  web:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "echo 'Attente que la base de données soit prête...' && while ! nc -z db 5432; do sleep 1; done && echo 'La base de données connectée. Démarrage de l'application...' && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: