# Generated by Django 5.2.1 on 2025-05-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='nom',
            new_name='title',
        ),
    ]
