name: Scrum CD
on: 
    workflow_run:
        workflows: ["Scrum CI"]
        types:
            - completed
jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:latest
                ports:
                    - 5432:5432
                env:
                    DATABASE_URL: postgres://postgres:2024@localhost:5432/scrum_db
                    DATABASE_HOST: localhost
                    DATABASE_PORT: 5432
                    DATABASE_USER: postgres
                    DATABASE_PASSWORD: 2024
                options: >-
                    --health-cmd "pg_isready -U postgres"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.11.8'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: simulate deployment
              run: |
                  echo "Deploiment de l'application sur le serveur de production"
                  echo "Connexion a la base de données"
                  echo "Execution des migrations"
                  echo "Lancement de l'application Django"
                  echo "L'application est deploiée avec succès"

            